
export const CHANGE_RADIO_CATEGORY = 'djradio/CHANGE_RADIO_CATEGORY'

export const CHANGE_RADIO_HOT_LIST = 'djradio/CHANGE_RADIO_HOT_LIST'

export const CHANGE_RADIO_RANKING = 'djradio/CHANGE_RADIO_RANKING'

export const CHANGE_RADIO_RECOMMEND = 'djradio/CHANGE_RADIO_RECOMMEND'
export const CHANGE_RADIO_EMOTION = 'djradio/CHANGE_RADIO_EMOTION'
export const CHANGE_RADIO_LIFE = 'djradio/CHANGE_RADIO_LIFE'
export const CHANGE_RADIO_TALKSHOW = 'djradio/CHANGE_RADIO_TALKSHOW'
